# Generated by Django 5.0 on 2024-06-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_comment_comment_content_remove_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
